<?php

/**
 * @file
 * Integrate Simplenews Content Selection with views and views bulk operations
 */

/**
 * Implementation of hook_action_info().
 */
function scs_views_action_info() {
  return array(
    'scs_views_create_newsletter_action' => array(
      'type' => 'node',
      'label' => t('Create newsletter'),
      'configurable' => TRUE,
      'behavior' => array('scs_views_create_newsletter'),
    ),
  );
}

/**
 * Configuration form for tis action. Not used as form, but used as a step to go to the node sorter.
 */
function scs_views_create_newsletter_action_form($form, $form_state, $context) {
  $form = array_merge($form, _scs_get_metadata_form($form));
  $nodes = array_keys($context['selection']);
  $form = array_merge($form, _scs_get_sorting_form($form, $nodes));
  return $form;
}

/**
 * Get the selected nodes and create a newsletter from it
 */
function scs_views_create_newsletter_action_submit($form, $form_state) {
  _scs_nodes_submit($form_state);
}
