<?php
  // $Id$
  
  /**
   * @file
   * Let's you select the content of a newsletter from a list of nodes
   */
  
  /**
   * Implementation of hook_menu
   */
  function simplenews_content_selection_menu() {
    $items = array();
    
    $items['admin/settings/simplenews/content_selection'] = array(
      'title' => 'Content Selection',
      'description' => 'Administrative settings for the content selection module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('simplenews_content_selection_admin_settings'),
      'access arguments' => array('administer content selection'),
      'file' => 'simplenews_content_selection.admin.inc',
    );
    
    $items['admin/content/simplenews/content_selection'] = array(
      'title' => 'Content Selection',
      'description' => 'Create a new newsletter by selection the content from the node list',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('simplenews_content_selection_selectlist'),
      'access arguments' => array('create with content selection'),
    );
    
    return $items;
  }
  
  /**
   * Implementation of hook_perm
   */
  function simplenews_content_select_perm() {
    return array('administer content selection', 'create with content selection');
  }
  
  /**
   * Content Selection node list
   */
  function simplenews_content_selection_selectlist() {
    //Get the data
    $nodes = _simplenews_content_selection_get_nodes();
    $newsletters = array();
    
    foreach (taxonomy_get_tree(variable_get('simplenews_vid', '')) as $newsletter) {
        $newsletters[$newsletter->tid] = $newsletter->name;
      }
    
    $form = array();
    
    $form['general'] = array(
      '#type' => 'fieldset',
      '#title' => t('General newsletter settings'),
    );
    
    $form['general']['subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Newsletter subject'),
      '#required' => TRUE,
    );
    
    $form['general']['newsletter'] = array(
      '#type' => 'radios',
      '#title' => t('Select newsletter to send to'),
      '#options' => $newsletters,
      '#required' => TRUE,
    );
    
    $form['nodes'] = array(
      '#type' => 'fieldset',
      '#title' => t('Select nodes'),
    );
    
    foreach ($nodes as $nid => $title) {
      $form['nodes']['nid_'. $nid] = array(
        '#type' => 'checkbox',
        '#title' => $title,
      );
    }
    
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Create newsletter'),
    );
    
    return $form;
  }
  
  /**
   * Validate the content selection form
   */
  function simplenews_content_selection_selectlist_validate($form, &$form_state) {
    //Check if there is at least one node selected, otherwise error
    $selected = FALSE;
    $first = '';
    
    foreach ($form_state['values'] as $field => $value) {
      if ($first != '') {
        $first = $field;
      }
      
      if (ereg('nid_', $field) && $value == 1) {
        $selected = TRUE;  
      }
    }
    
    if ($selected == FALSE) {
      form_set_error($first, t('You have to select at least one node'));
    }
  }
  
  /**
   * Submit the content selection form
   */
  function simplenews_content_selection_selectlist_submit($form, &$form_state) {
    $nodes = array();
    
    //Get the selected nodes
    foreach ($form_state['values'] as $field => $value) {
      if (ereg('nid_', $field) && $value == 1) {
        $field = explode('_', $field);
        $nodes[] = $field[1];
      }
    }

    _simplenews_content_selection_create($form_state['values']['subject'], $form_state['values']['newsletter'], $nodes);
  }
  
  /**
   * Interal to get the nodes available for selection
   */
  function _simplenews_content_selection_get_nodes() {
    //Get the types
    $types = variable_get('scs_content_types', array());
    
    foreach ($types as $type => $selected) {
      if ($selected == '0') {
        unset($types[$type]);
      }
    }
    
    $types = array_keys($types);
    
    //Get the nodes
    $nodes = array();
    
    $p = db_placeholders($types, "varchar");
    $qry = "SELECT nid, title FROM {node} WHERE type IN ($p)";
    
    $result = db_query($qry, $types);
    
    while ($row = db_fetch_object($result)) {
      $nodes[$row->nid] = $row->title;
    }
    
    return $nodes;
  }
  
  /**
   * Interal that creates the newsletter
   */
  function _simplenews_content_selection_create($title, $newsletter, $nodes) {
    global $user;
    
    //Create the body
    $body = array();
    $items = array();
    
    foreach ($nodes as $nid) {
      $node = node_load(array('nid' => $nid));
      $items[] = theme('simplenews_content_selection_newsletter_item', $node);
    }
    
    $body = implode("\n", $items);
    
    //Get the term
    $term = taxonomy_get_term($newsletter);
    
    //Create the newsletter node
    $node = new stdClass();
    $node->body = $body;
      $node->uid = $user->uid;
      $node->title = $title;
      $node->type = 'simplenews';
      $node->teaser = node_teaser($body);
      $node->status = 1;
      $node->revision = 1;
      $node->promote = 0;
      $node->comment = 0;
      $node->created = time();
      $node->changed = time();
      $node->taxonomy[$newsletter] = $term;
      $node->priority = 0;
      $node->receipt = 0;
      //$node->simplenews = array('send' => SIMPLENEWS_COMMAND_SEND_NOW); // Necessary to send out the newsletter without further user interaction.
      
      node_save($node);
      
      //Redirect to the edit of this node
      drupal_goto('node/'. $node->nid .'/edit');
  }
  
  /**
   * Implementation of hook_theme
   */
  function simplenews_content_selection_theme() {
    return array(
      'simplenews_content_selection_newsletter_item' => array(
        'arguments' => array(
          'node' => NULL,
        ),
        'file' => 'simplenews_content_selection.theme.inc',
      ),
      'simplenews_content_selection_selectlist' => array(
        'arguments' => array(
          'form' => NULL,
        ),
        'file' => 'simplenews_content_selection.theme.inc',
      ),
    );
  }
  